-- AulaLibre base schema: users, blocks, rooms, schedules, room requests.

CREATE TABLE app_users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    VARCHAR(100) NOT NULL,
    last_name     VARCHAR(100) NOT NULL,
    email         VARCHAR(150) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL,
    CONSTRAINT uk_app_users_email UNIQUE (email)
);

CREATE TABLE blocks (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(10)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    description   VARCHAR(255),
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL,
    CONSTRAINT uk_blocks_code UNIQUE (code)
);

CREATE TABLE rooms (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    block_id      BIGINT       NOT NULL,
    floor         INTEGER      NOT NULL,
    capacity      INTEGER      NOT NULL,
    type          VARCHAR(20)  NOT NULL,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL,
    CONSTRAINT fk_rooms_block FOREIGN KEY (block_id) REFERENCES blocks (id)
);

CREATE INDEX idx_rooms_block_id ON rooms (block_id);

CREATE TABLE schedules (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id               BIGINT       NOT NULL,
    day_of_week           VARCHAR(15)  NOT NULL,
    start_time            TIME         NOT NULL,
    end_time              TIME         NOT NULL,
    subject_or_activity   VARCHAR(150) NOT NULL,
    active                BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at            TIMESTAMP    NOT NULL,
    updated_at            TIMESTAMP    NOT NULL,
    CONSTRAINT fk_schedules_room FOREIGN KEY (room_id) REFERENCES rooms (id)
);

CREATE INDEX idx_schedules_room_id ON schedules (room_id);

CREATE TABLE room_requests (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professor_id      BIGINT       NOT NULL,
    room_id           BIGINT       NOT NULL,
    date              DATE         NOT NULL,
    start_time        TIME         NOT NULL,
    end_time          TIME         NOT NULL,
    reason            VARCHAR(30)  NOT NULL,
    observation       VARCHAR(500),
    status            VARCHAR(20)  NOT NULL,
    reviewed_by       BIGINT,
    reviewed_at       TIMESTAMP,
    rejection_reason  VARCHAR(500),
    created_at        TIMESTAMP    NOT NULL,
    updated_at        TIMESTAMP    NOT NULL,
    CONSTRAINT fk_room_requests_professor FOREIGN KEY (professor_id) REFERENCES app_users (id),
    CONSTRAINT fk_room_requests_room FOREIGN KEY (room_id) REFERENCES rooms (id),
    CONSTRAINT fk_room_requests_reviewer FOREIGN KEY (reviewed_by) REFERENCES app_users (id)
);

CREATE INDEX idx_room_requests_professor_id ON room_requests (professor_id);
CREATE INDEX idx_room_requests_room_id ON room_requests (room_id);
CREATE INDEX idx_room_requests_status ON room_requests (status);
